app = "hominio-voice"
primary_region = "ord"
vm.size = "a100-40gb"

[build]
dockerfile = "Dockerfile"

[env]
CUDA_VISIBLE_DEVICES = "0"
NVIDIA_VISIBLE_DEVICES = "all"
NVIDIA_DRIVER_CAPABILITIES = "compute,utility"
FORCE_CUDA = "1"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
OMP_NUM_THREADS = "1"
MKL_NUM_THREADS = "1"
TOKENIZERS_PARALLELISM = "false"
PYTORCH_NUM_THREADS = "1"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = false
processes = ["app"]

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/health"
