app = "hominio-voice"
primary_region = "ord"

[build]
dockerfile = "Dockerfile"

[vm]
size = "a100-40gb"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/health"
